//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.42000
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

using NMF.Collections.Generic;
using NMF.Collections.ObjectModel;
using NMF.Expressions;
using NMF.Expressions.Linq;
using NMF.Models;
using NMF.Models.Collections;
using NMF.Models.Expressions;
using NMF.Models.Meta;
using NMF.Models.Repository;
using NMF.Serialization;
using NMF.Utilities;
using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;
using System.ComponentModel;
using System.Diagnostics;
using System.Globalization;
using System.Linq;
using TTC2021.OclToSql.Ocl.Dm;

namespace TTC2021.OclToSql.Ocl.Exp
{
    
    
    /// <summary>
    /// The public interface for CallExp
    /// </summary>
    [DefaultImplementationTypeAttribute(typeof(CallExp))]
    [XmlDefaultImplementationTypeAttribute(typeof(CallExp))]
    [ModelRepresentationClassAttribute("http://www.example.org/ocl#//exp/CallExp")]
    public interface ICallExp : IModelElement, IOclExpression
    {
        
        /// <summary>
        /// The source property
        /// </summary>
        [BrowsableAttribute(false)]
        [XmlElementNameAttribute("source")]
        [XmlAttributeAttribute(false)]
        [ContainmentAttribute()]
        [XmlOppositeAttribute("appliedElement")]
        IOclExpression Source
        {
            get;
            set;
        }
        
        /// <summary>
        /// Gets fired before the Source property changes its value
        /// </summary>
        event System.EventHandler<ValueChangedEventArgs> SourceChanging;
        
        /// <summary>
        /// Gets fired when the Source property changed its value
        /// </summary>
        event System.EventHandler<ValueChangedEventArgs> SourceChanged;
    }
}

