//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.42000
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

using NMF.Collections.Generic;
using NMF.Collections.ObjectModel;
using NMF.Expressions;
using NMF.Expressions.Linq;
using NMF.Models;
using NMF.Models.Collections;
using NMF.Models.Expressions;
using NMF.Models.Meta;
using NMF.Models.Repository;
using NMF.Serialization;
using NMF.Utilities;
using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;
using System.ComponentModel;
using System.Diagnostics;
using System.Globalization;
using System.Linq;
using TTC2021.OclToSql.Ocl.Dm;

namespace TTC2021.OclToSql.Ocl.Exp
{
    
    
    /// <summary>
    /// The public interface for IteratorExp
    /// </summary>
    [DefaultImplementationTypeAttribute(typeof(IteratorExp))]
    [XmlDefaultImplementationTypeAttribute(typeof(IteratorExp))]
    [ModelRepresentationClassAttribute("http://www.example.org/ocl#//exp/IteratorExp")]
    public interface IIteratorExp : IModelElement, ICallExp
    {
        
        /// <summary>
        /// The kind property
        /// </summary>
        [DisplayNameAttribute("kind")]
        [CategoryAttribute("IteratorExp")]
        [XmlElementNameAttribute("kind")]
        [XmlAttributeAttribute(true)]
        IteratorKind Kind
        {
            get;
            set;
        }
        
        /// <summary>
        /// The body property
        /// </summary>
        [BrowsableAttribute(false)]
        [XmlElementNameAttribute("body")]
        [XmlAttributeAttribute(false)]
        [ContainmentAttribute()]
        [XmlOppositeAttribute("loopBodyOwner")]
        IOclExpression Body
        {
            get;
            set;
        }
        
        /// <summary>
        /// The iterator property
        /// </summary>
        [DesignerSerializationVisibilityAttribute(DesignerSerializationVisibility.Content)]
        [BrowsableAttribute(false)]
        [XmlElementNameAttribute("iterator")]
        [XmlAttributeAttribute(false)]
        [ContainmentAttribute()]
        [XmlOppositeAttribute("loopExp")]
        [ConstantAttribute()]
        IOrderedSetExpression<IVariable> Iterator
        {
            get;
        }
        
        /// <summary>
        /// Gets fired before the Kind property changes its value
        /// </summary>
        event System.EventHandler<ValueChangedEventArgs> KindChanging;
        
        /// <summary>
        /// Gets fired when the Kind property changed its value
        /// </summary>
        event System.EventHandler<ValueChangedEventArgs> KindChanged;
        
        /// <summary>
        /// Gets fired before the Body property changes its value
        /// </summary>
        event System.EventHandler<ValueChangedEventArgs> BodyChanging;
        
        /// <summary>
        /// Gets fired when the Body property changed its value
        /// </summary>
        event System.EventHandler<ValueChangedEventArgs> BodyChanged;
    }
}

