//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.42000
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

using NMF.Collections.Generic;
using NMF.Collections.ObjectModel;
using NMF.Expressions;
using NMF.Expressions.Linq;
using NMF.Models;
using NMF.Models.Collections;
using NMF.Models.Expressions;
using NMF.Models.Meta;
using NMF.Models.Repository;
using NMF.Serialization;
using NMF.Utilities;
using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;
using System.ComponentModel;
using System.Diagnostics;
using System.Linq;

namespace TTC2021.OclToSql.Sql
{
    
    
    /// <summary>
    /// The public interface for SubSelect
    /// </summary>
    [DefaultImplementationTypeAttribute(typeof(SubSelect))]
    [XmlDefaultImplementationTypeAttribute(typeof(SubSelect))]
    [ModelRepresentationClassAttribute("http://www.example.org/sql#//SubSelect")]
    public interface ISubSelect : IModelElement, IExpression, IFromItem
    {
        
        /// <summary>
        /// The alias property
        /// </summary>
        [BrowsableAttribute(false)]
        [XmlElementNameAttribute("alias")]
        [XmlAttributeAttribute(false)]
        [ContainmentAttribute()]
        IAlias Alias
        {
            get;
            set;
        }
        
        /// <summary>
        /// The selectBody property
        /// </summary>
        [BrowsableAttribute(false)]
        [XmlElementNameAttribute("selectBody")]
        [XmlAttributeAttribute(false)]
        [ContainmentAttribute()]
        IPlainSelect SelectBody
        {
            get;
            set;
        }
        
        /// <summary>
        /// Gets fired before the Alias property changes its value
        /// </summary>
        event System.EventHandler<ValueChangedEventArgs> AliasChanging;
        
        /// <summary>
        /// Gets fired when the Alias property changed its value
        /// </summary>
        event System.EventHandler<ValueChangedEventArgs> AliasChanged;
        
        /// <summary>
        /// Gets fired before the SelectBody property changes its value
        /// </summary>
        event System.EventHandler<ValueChangedEventArgs> SelectBodyChanging;
        
        /// <summary>
        /// Gets fired when the SelectBody property changed its value
        /// </summary>
        event System.EventHandler<ValueChangedEventArgs> SelectBodyChanged;
    }
}

