//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.42000
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

using NMF.Collections.Generic;
using NMF.Collections.ObjectModel;
using NMF.Expressions;
using NMF.Expressions.Linq;
using NMF.Models;
using NMF.Models.Collections;
using NMF.Models.Expressions;
using NMF.Models.Meta;
using NMF.Models.Repository;
using NMF.Serialization;
using NMF.Utilities;
using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;
using System.ComponentModel;
using System.Diagnostics;
using System.Linq;

namespace TTC2021.OclToSql.Sql
{
    
    
    /// <summary>
    /// The public interface for WhenClause
    /// </summary>
    [DefaultImplementationTypeAttribute(typeof(WhenClause))]
    [XmlDefaultImplementationTypeAttribute(typeof(WhenClause))]
    [ModelRepresentationClassAttribute("http://www.example.org/sql#//WhenClause")]
    public interface IWhenClause : IModelElement
    {
        
        /// <summary>
        /// The whenExp property
        /// </summary>
        [BrowsableAttribute(false)]
        [XmlElementNameAttribute("whenExp")]
        [XmlAttributeAttribute(false)]
        [ContainmentAttribute()]
        IExpression WhenExp
        {
            get;
            set;
        }
        
        /// <summary>
        /// The thenExp property
        /// </summary>
        [BrowsableAttribute(false)]
        [XmlElementNameAttribute("thenExp")]
        [XmlAttributeAttribute(false)]
        [ContainmentAttribute()]
        IExpression ThenExp
        {
            get;
            set;
        }
        
        /// <summary>
        /// Gets fired before the WhenExp property changes its value
        /// </summary>
        event System.EventHandler<ValueChangedEventArgs> WhenExpChanging;
        
        /// <summary>
        /// Gets fired when the WhenExp property changed its value
        /// </summary>
        event System.EventHandler<ValueChangedEventArgs> WhenExpChanged;
        
        /// <summary>
        /// Gets fired before the ThenExp property changes its value
        /// </summary>
        event System.EventHandler<ValueChangedEventArgs> ThenExpChanging;
        
        /// <summary>
        /// Gets fired when the ThenExp property changed its value
        /// </summary>
        event System.EventHandler<ValueChangedEventArgs> ThenExpChanged;
    }
}

