<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="sql" nsURI="http://www.example.org/sql" nsPrefix="sql">
  <eClassifiers xsi:type="ecore:EClass" name="EStatement" abstract="true" interface="true"/>
  <eClassifiers xsi:type="ecore:EClass" name="ESelect" eSuperTypes="#//EStatement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="selectBody" lowerBound="1"
        eType="#//ESelectBody" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ESelectBody" abstract="true" interface="true"/>
  <eClassifiers xsi:type="ecore:EClass" name="EPlainSelect" eSuperTypes="#//ESelectBody">
    <eStructuralFeatures xsi:type="ecore:EReference" name="distinct" eType="#//EDistinct"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="selectItems" lowerBound="1"
        upperBound="-1" eType="#//ESelectItem" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="fromItem" eType="#//EFromItem"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="joins" upperBound="-1"
        eType="#//EJoin" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="where" eType="#//EExpression"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="groupBy" eType="#//EGroupByElement"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="having" eType="#//EExpression"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="EDistinct">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="useUnique" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="onSelectItems" upperBound="-1"
        eType="#//ESelectItem" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="EGroupByElement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="groupByExpressions" upperBound="-1"
        eType="#//EExpression" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="EJoin">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="outer" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="right" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="left" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="natural" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="full" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="inner" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="simple" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="cross" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="semi" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="straight" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="apply" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="rightItem" lowerBound="1"
        eType="#//EFromItem" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="onExpression" eType="#//EExpression"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="EAlias">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="EExpression" abstract="true" interface="true"/>
  <eClassifiers xsi:type="ecore:EClass" name="EBinaryExpression" abstract="true" eSuperTypes="#//EExpression">
    <eStructuralFeatures xsi:type="ecore:EReference" name="leftExpression" lowerBound="1"
        eType="#//EExpression" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="rightExpression" lowerBound="1"
        eType="#//EExpression" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="EAndExpression" eSuperTypes="#//EBinaryExpression"/>
  <eClassifiers xsi:type="ecore:EClass" name="EOrExpression" eSuperTypes="#//EBinaryExpression"/>
  <eClassifiers xsi:type="ecore:EClass" name="EComparisonOperator" abstract="true"
      eSuperTypes="#//EBinaryExpression">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="operator" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="EEqualsTo" eSuperTypes="#//EComparisonOperator"/>
  <eClassifiers xsi:type="ecore:EClass" name="EGreaterThan" eSuperTypes="#//EComparisonOperator"/>
  <eClassifiers xsi:type="ecore:EClass" name="EGreaterThanEquals" eSuperTypes="#//EComparisonOperator"/>
  <eClassifiers xsi:type="ecore:EClass" name="EMinorThan" eSuperTypes="#//EComparisonOperator"/>
  <eClassifiers xsi:type="ecore:EClass" name="EMinorThanEquals" eSuperTypes="#//EComparisonOperator"/>
  <eClassifiers xsi:type="ecore:EClass" name="ENotEqualsTo" eSuperTypes="#//EComparisonOperator"/>
  <eClassifiers xsi:type="ecore:EClass" name="ESelectItem" abstract="true" interface="true"/>
  <eClassifiers xsi:type="ecore:EClass" name="EAllColumns" eSuperTypes="#//ESelectItem"/>
  <eClassifiers xsi:type="ecore:EClass" name="ESelectExpressionItem" eSuperTypes="#//ESelectItem">
    <eStructuralFeatures xsi:type="ecore:EReference" name="alias" eType="#//EAlias"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="expression" lowerBound="1"
        eType="#//EExpression" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="EFromItem" abstract="true" interface="true"/>
  <eClassifiers xsi:type="ecore:EClass" name="ETable" eSuperTypes="#//EFromItem">
    <eStructuralFeatures xsi:type="ecore:EReference" name="alias" eType="#//EAlias"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ESubSelect" eSuperTypes="#//EFromItem #//EExpression">
    <eStructuralFeatures xsi:type="ecore:EReference" name="alias" eType="#//EAlias"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="selectBody" lowerBound="1"
        eType="#//ESelectBody" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ENotExpression" eSuperTypes="#//EExpression">
    <eStructuralFeatures xsi:type="ecore:EReference" name="expression" lowerBound="1"
        eType="#//EExpression" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ELongValue" eSuperTypes="#//EExpression">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="value" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//ELongObject"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ENullValue" eSuperTypes="#//EExpression"/>
  <eClassifiers xsi:type="ecore:EClass" name="EIsNullExpression" eSuperTypes="#//EExpression">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="not" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="leftExpression" lowerBound="1"
        eType="#//EExpression" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="EFunction" eSuperTypes="#//EExpression">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="allColumns" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="distinct" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="parameters" eType="#//EExpressionList"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="EColumn" eSuperTypes="#//EExpression">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="columnName" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="table" eType="#//ETable"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ECaseExpression" eSuperTypes="#//EExpression">
    <eStructuralFeatures xsi:type="ecore:EReference" name="switchExpression" eType="#//EExpression"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="elseExpression" eType="#//EExpression"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="whenClauses" upperBound="-1"
        eType="#//EWhenClause" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="EWhenClause" eSuperTypes="#//EExpression">
    <eStructuralFeatures xsi:type="ecore:EReference" name="whenExpression" lowerBound="1"
        eType="#//EExpression" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="thenExpression" lowerBound="1"
        eType="#//EExpression" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="EStringValue" eSuperTypes="#//EExpression">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="value" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="EExpressionList">
    <eStructuralFeatures xsi:type="ecore:EReference" name="expressions" upperBound="-1"
        eType="#//EExpression" containment="true"/>
  </eClassifiers>
</ecore:EPackage>
